apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: practice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: practice1-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: practice1-config
                  key: MARIADB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: practice1-config
                  key: MARIADB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: practice1-secret
                  key: MARIADB_PASSWORD
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: practice1
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
