apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: practice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          env:
            - name: LDAP_ORGANISATION
              valueFrom:
                configMapKeyRef:
                  name: practice1-config
                  key: LDAP_ORGANISATION
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: practice1-config
                  key: LDAP_DOMAIN
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: practice1-secret
                  key: LDAP_ADMIN_PASSWORD
          ports:
            - containerPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: practice1
spec:
  selector:
    app: openldap
  ports:
    - port: 389
      targetPort: 389
